### ISSUE TITLE
What are unhandled vote questions, and should I worry about them?

### ISSUE THREAD

**Issue by martinburch** [unitedstates/congress#158]
(congress)cmb:congress burchc$ ./run votes --congress=114 --session=2015
    Going to fetch 199 votes from congress #114 session 2015
    Unhandled vote question: Table Motion to Refer
    Unhandled vote question: Call by States

It looks like this is an effort to assign vote question text to categories, although this message isn't documented in the wiki. I see there's some effort to handle (i.e. normalize) the "Call by States" question in PR #155

Does this (warning?) message mean [the vote `type` or `category`](https://github.com/unitedstates/congress/wiki/Votes#what-the-vote-was-about) will be blank? Will it have any other effects?

**Comment by handlers** [comment]
You are correct that this is an effort to assign vote question text to categories. In the event of an unhandled question, you'll see `"category": "unknown"` in the scraper's JSON output (as with, for example, h1). This is in distinction to a vote on something like h2, which has `"category": "leadership"`.

Because the scrapers are not tied to any particular implementation, it's hard to say whether or not one should worry about an 'unknown' value in this field. But within the scrapers themselves, nothing catastrophic will happen.

**Comment by handlers** [comment]
I'm going to close this issue because it's not actionable, but feel free to keep hitting this thread!
