### ISSUE TITLE
Bulk legislative status data

### ISSUE THREAD

**Issue by dwillis** [unitedstates/congress#165]
Now that [GPO has released bulk data](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS) for 113th and 114th Congresses, how should it be incorporated into this project?

**Comment by crdunwel** [comment]
I unfortunately wasn't around in DC for the meeting where the bulk data release format was discussed. Scanning the Bill Status XML it appears most fields we currently collect are present - is that correct? Are there any fields missing or new fields added? So long as the [output of the scraper](https://github.com/unitedstates/congress/blob/master/tasks/bill_info.py#L214) retains the same format then transition should be fairly painless by pulling the XMLs, parsing them, and packing them into the correct fields.

**Comment by JoshData** [comment]
It has all of the data that we're currently pulling from THOMAS, yes. The hard part is getting it. @usgpo said at the meeting that they would use sitemaps to indicate which files were updated, but that doesn't seem to be in place. I asked Kirsten to see what happened there. (The fdsys scraper here could be used to efficiently download changed files if they publish a sitemap.)

I'd like our scrips to ingest the new data and export it in exactly the same format we have now, as Clayton says. I don't really want to rebuild GovTrack's data pipeline, break data compatibility with anyone using this/GovTrack's data, or have two data formats for historical (pre-113th Congress) and current bills.

Also, unless/until historical bill data is released and until THOMAS is actually shut down, we should keep the old scraper around.

**Comment by crdunwel** [comment]
@JoshData  :+1: Yeah if we had a sitemap then that would clearly be much more optimum than recursively scraping the bulk data pages for links. And yes, we would prefer not to rewrite or diverge ingestion pipelines either so I don't think it would hurt to maintain current formats, unless somebody has a compelling reason otherwise?

Let us know when Kristen gets back to you. If there are no plans for a sitemap then \\\_(ツ)_/¯ guess we recursively scrape?

**Comment by konklone** [comment]
FWIW, GPO's sitemaps are documented here: https://github.com/usgpo/sitemap/

I don't think there's anything new here, but for the benefit of anyone reading the thread, GPO has opened up their new FDSys replacement, govinfo.gov. It includes [their announcement](https://www.govinfo.gov/features/featured-content/bill-status-bulk-data), a [Develoepr Hub](https://www.govinfo.gov/developers), and a [Congress.gov-style search engine](https://govinfo.gov/app/search/#search?st=publishdate:range(2016-02-24,2016-02-25) AND collection:bills).

**Comment by crdunwel** [comment]
Thanks @konklone . Super quick browse yields https://www.gpo.gov/smap/bulkdata/sitemapindex.xml looks to be what we want?

**Comment by JoshData** [comment]
Ahha, I was looking in the wrong place. (@gullicksonk, nevermind my email about the sitemaps - there it is.)

**Comment by crdunwel** [comment]
Anybody start working on this? May be we could start by identifying which scripts will be definitely be affected and the methods ripe for modification?

**Comment by JoshData** [comment]
Since I wrote fdsys.py, I was thinking of starting there and a) seeing if it will download all of the new XML, and b) maybe overhauling the script because it's a bit pasta-like (spaghetti code). The script is meant to be a very efficient fetcher, based on GPO sitemaps to download just modified files.

Then maybe someone else can focus on the XML files themselves.

**Comment by JoshData** [comment]
I have a PR (^) that re-writes `fdsys.py` so that it can download the bulk data files.

**Comment by crdunwel** [comment]
@JoshData nice, was about to ask on status. Will check it out today and start handling the XML.

**Comment by dwillis** [comment]
I've been dealing with the XML this week - in most cases it makes pretty good sense, but I'm curious what folks think about the data around actions and amendments in particular, where there seem to be some more aspects of the data than I (at least) got from scraping. For example, this is a bill action:
![screen shot 2016-03-22 at 12 58 12 pm](https://cloud.githubusercontent.com/assets/2214/13960204/c7ac02fc-f02d-11e5-8ea0-5e238b2905dd.png)

**Comment by JoshData** [comment]
What's the issue?

**Comment by dwillis** [comment]
For actions there's no issue - it's a matter of more "fields" being available, I think. But for amendments, the XML doesn't appear to contain some elements that I'd like, such as bioguide_id for amendment authors.

**Comment by JoshData** [comment]
On top of more fields, there are also cases where there are more actual actions. Apparently what we see on Congress.gov is filtered and the underlying data has in some cases multiple entries for the same logical thing because the action data is coming from multiple sources. (This is a good thing - more data. I'm not sure if it will impact our efforts.)

> But for amendments, the XML doesn't appear to contain some elements that I'd like, such as bioguide_id for amendment authors.

Well that's not good at all.

**Comment by dwillis** [comment]
I've opened an issue [here](https://github.com/usgpo/bill-status/issues/3) for amendments.

**Comment by JoshData** [comment]
PR in #175.
